# Generated by Django 4.0.1 on 2022-02-05 11:34

import app_main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=app_main.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(choices=[('long', 'Long Run ToDo'), ('medium', 'Medium Run ToDo'), ('short', 'Short Run ToDo'), ('other', 'Others ToDo')], default='other', max_length=32)),
                ('titel', models.CharField(blank=True, max_length=150)),
                ('importance', models.CharField(blank=True, max_length=150)),
                ('detailed_description', models.TextField()),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'Rent Spending'), ('insurance', 'Insurance Spending'), ('tax', 'Tax Spending'), ('medical', 'Medical Spending'), ('bills', 'Bills Spending'), ('internet', 'Internet Spending'), ('food', 'Food Spending'), ('cloth', 'Cloth Spending'), ('wants', 'Wants Spending'), ('emergency', 'Emergency Spending'), ('others', 'Others Spending')], default='others', max_length=32)),
                ('value', models.FloatField(default=0.0)),
                ('titel', models.CharField(blank=True, max_length=150)),
                ('importance', models.CharField(blank=True, max_length=150)),
                ('detailed_description', models.TextField()),
                ('date_of_spending', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
